version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tempdbname
      POSTGRES_USER: tempusername
      POSTGRES_PASSWORD: temppassword

  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  postgres_data:
