version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tempdbname
      POSTGRES_USER: tempusername
      POSTGRES_PASSWORD: temppassword

  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next 
    ports:
      - "3000:3000"
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - server

volumes:
  postgres_data:
