# Generated by Django 5.0.2 on 2024-02-28 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255, unique=True)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPassword', models.CharField(max_length=255)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('promptID', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.user')),
            ],
            options={
                'db_table': 'Prompts',
            },
        ),
    ]
