# Generated by Django 5.0.2 on 2024-03-01 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255, unique=True)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPassword', models.CharField(max_length=255)),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('promptID', models.AutoField(primary_key=True, serialize=False)),
                ('promptDetails', models.TextField()),
                ('creationTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.user')),
            ],
        ),
    ]
